name: release new version
on:
  push:
    branches:
      - 'main'
    paths:
      - 'version.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current branch
        uses: actions/checkout@v2
      - name: read version.txt
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - name: create a new tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.content }}
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: clean build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.content }}
          prerelease: true
          draft: true
          files: infrastructor-cli/build/distributions/*.zip